#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiesgoLaboral.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="laboral")]
	public partial class LaboralMembershipUserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LaboralMembershipUserDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LaboralMembershipUserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaboralMembershipUserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaboralMembershipUserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LaboralMembershipUserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UserErrorTable> UserErrorTables
		{
			get
			{
				return this.GetTable<UserErrorTable>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsUpdUserDetails")]
		public int InsUpdUserDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApPaterno", DbType="VarChar(40)")] string apPaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApMaterno", DbType="VarChar(40)")] string apMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="VarChar(40)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(40)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colonia", DbType="VarChar(40)")] string colonia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Municipio", DbType="VarChar(40)")] string municipio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(40)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPostal", DbType="Decimal(18,0)")] System.Nullable<decimal> codigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelFijo", DbType="VarChar(15)")] string telFijo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelMovil", DbType="VarChar(15)")] string telMovil)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, nombre, apPaterno, apMaterno, company, direccion, colonia, municipio, estado, codigoPostal, telFijo, telMovil);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersDetailsbyID")]
		public ISingleResult<UsersDetailsbyIDResult> UsersDetailsbyID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<UsersDetailsbyIDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User
	{
		
		private System.Guid _UserId;
		
		private string _Company;
		
		private string _Nombre;
		
		private string _ApPaterno;
		
		private string _ApMaterno;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Direccion;
		
		private string _Colonia;
		
		private string _Municipio;
		
		private string _Estado;
		
		private decimal _CodigoPostal;
		
		private string _TelFijo;
		
		private string _TelExtension;
		
		private string _TelMovil;
		
		private System.Nullable<int> _RoleId;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPaterno", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ApPaterno
		{
			get
			{
				return this._ApPaterno;
			}
			set
			{
				if ((this._ApPaterno != value))
				{
					this._ApPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApMaterno", DbType="NChar(20)")]
		public string ApMaterno
		{
			get
			{
				return this._ApMaterno;
			}
			set
			{
				if ((this._ApMaterno != value))
				{
					this._ApMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(80)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colonia", DbType="NVarChar(80)")]
		public string Colonia
		{
			get
			{
				return this._Colonia;
			}
			set
			{
				if ((this._Colonia != value))
				{
					this._Colonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(10)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="Decimal(5,0) NOT NULL")]
		public decimal CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this._CodigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelFijo", DbType="VarChar(15)")]
		public string TelFijo
		{
			get
			{
				return this._TelFijo;
			}
			set
			{
				if ((this._TelFijo != value))
				{
					this._TelFijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelExtension", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelExtension
		{
			get
			{
				return this._TelExtension;
			}
			set
			{
				if ((this._TelExtension != value))
				{
					this._TelExtension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelMovil", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelMovil
		{
			get
			{
				return this._TelMovil;
			}
			set
			{
				if ((this._TelMovil != value))
				{
					this._TelMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int")]
		public System.Nullable<int> RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this._RoleId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserErrorTable")]
	public partial class UserErrorTable
	{
		
		private System.Guid _UserId;
		
		private string _Company;
		
		private string _Nombre;
		
		private string _ApPaterno;
		
		private string _ApMaterno;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Direccion;
		
		private string _Colonia;
		
		private string _Municipio;
		
		private string _Estado;
		
		private decimal _CodigoPostal;
		
		private string _TelFijo;
		
		private string _TelExtension;
		
		private string _TelMovil;
		
		private System.Nullable<int> _RoleId;
		
		public UserErrorTable()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPaterno", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ApPaterno
		{
			get
			{
				return this._ApPaterno;
			}
			set
			{
				if ((this._ApPaterno != value))
				{
					this._ApPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApMaterno", DbType="NChar(20)")]
		public string ApMaterno
		{
			get
			{
				return this._ApMaterno;
			}
			set
			{
				if ((this._ApMaterno != value))
				{
					this._ApMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(80)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colonia", DbType="NVarChar(80)")]
		public string Colonia
		{
			get
			{
				return this._Colonia;
			}
			set
			{
				if ((this._Colonia != value))
				{
					this._Colonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(10)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="Decimal(5,0) NOT NULL")]
		public decimal CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this._CodigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelFijo", DbType="VarChar(15)")]
		public string TelFijo
		{
			get
			{
				return this._TelFijo;
			}
			set
			{
				if ((this._TelFijo != value))
				{
					this._TelFijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelExtension", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelExtension
		{
			get
			{
				return this._TelExtension;
			}
			set
			{
				if ((this._TelExtension != value))
				{
					this._TelExtension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelMovil", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TelMovil
		{
			get
			{
				return this._TelMovil;
			}
			set
			{
				if ((this._TelMovil != value))
				{
					this._TelMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int")]
		public System.Nullable<int> RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this._RoleId = value;
				}
			}
		}
	}
	
	public partial class UsersDetailsbyIDResult
	{
		
		private string _Company;
		
		private string _Nombre;
		
		private string _ApPaterno;
		
		private string _ApMaterno;
		
		private string _Direccion;
		
		private string _Colonia;
		
		private string _Municipio;
		
		private string _Estado;
		
		private System.Nullable<decimal> _CodigoPostal;
		
		private string _TelFijo;
		
		private string _TelExtension;
		
		private string _TelMovil;
		
		private System.Nullable<int> _RoleId;
		
		public UsersDetailsbyIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPaterno", DbType="NChar(20)")]
		public string ApPaterno
		{
			get
			{
				return this._ApPaterno;
			}
			set
			{
				if ((this._ApPaterno != value))
				{
					this._ApPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApMaterno", DbType="NChar(20)")]
		public string ApMaterno
		{
			get
			{
				return this._ApMaterno;
			}
			set
			{
				if ((this._ApMaterno != value))
				{
					this._ApMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(80)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colonia", DbType="NVarChar(80)")]
		public string Colonia
		{
			get
			{
				return this._Colonia;
			}
			set
			{
				if ((this._Colonia != value))
				{
					this._Colonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(10)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this._CodigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelFijo", DbType="VarChar(15)")]
		public string TelFijo
		{
			get
			{
				return this._TelFijo;
			}
			set
			{
				if ((this._TelFijo != value))
				{
					this._TelFijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelExtension", DbType="VarChar(15)")]
		public string TelExtension
		{
			get
			{
				return this._TelExtension;
			}
			set
			{
				if ((this._TelExtension != value))
				{
					this._TelExtension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelMovil", DbType="VarChar(15)")]
		public string TelMovil
		{
			get
			{
				return this._TelMovil;
			}
			set
			{
				if ((this._TelMovil != value))
				{
					this._TelMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int")]
		public System.Nullable<int> RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this._RoleId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
