//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace pequenoModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pequenoEntities6 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pequenoEntities6 object using the connection string found in the 'pequenoEntities6' section of the application configuration file.
        /// </summary>
        public pequenoEntities6() : base("name=pequenoEntities6", "pequenoEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pequenoEntities6 object.
        /// </summary>
        public pequenoEntities6(string connectionString) : base(connectionString, "pequenoEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pequenoEntities6 object.
        /// </summary>
        public pequenoEntities6(EntityConnection connection) : base(connection, "pequenoEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Demandado> Demandadoes
        {
            get
            {
                if ((_Demandadoes == null))
                {
                    _Demandadoes = base.CreateObjectSet<Demandado>("Demandadoes");
                }
                return _Demandadoes;
            }
        }
        private ObjectSet<Demandado> _Demandadoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Expediente> Expedientes
        {
            get
            {
                if ((_Expedientes == null))
                {
                    _Expedientes = base.CreateObjectSet<Expediente>("Expedientes");
                }
                return _Expedientes;
            }
        }
        private ObjectSet<Expediente> _Expedientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Junta> Juntas
        {
            get
            {
                if ((_Juntas == null))
                {
                    _Juntas = base.CreateObjectSet<Junta>("Juntas");
                }
                return _Juntas;
            }
        }
        private ObjectSet<Junta> _Juntas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Demandadoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDemandadoes(Demandado demandado)
        {
            base.AddObject("Demandadoes", demandado);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Expedientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExpedientes(Expediente expediente)
        {
            base.AddObject("Expedientes", expediente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Juntas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJuntas(Junta junta)
        {
            base.AddObject("Juntas", junta);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pequenoModel", Name="Demandado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Demandado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Demandado object.
        /// </summary>
        /// <param name="cve_demandado">Initial value of the cve_demandado property.</param>
        public static Demandado CreateDemandado(global::System.Decimal cve_demandado)
        {
            Demandado demandado = new Demandado();
            demandado.cve_demandado = cve_demandado;
            return demandado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cve_demandado
        {
            get
            {
                return _cve_demandado;
            }
            set
            {
                if (_cve_demandado != value)
                {
                    Oncve_demandadoChanging(value);
                    ReportPropertyChanging("cve_demandado");
                    _cve_demandado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cve_demandado");
                    Oncve_demandadoChanged();
                }
            }
        }
        private global::System.Decimal _cve_demandado;
        partial void Oncve_demandadoChanging(global::System.Decimal value);
        partial void Oncve_demandadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Desc_demandado
        {
            get
            {
                return _Desc_demandado;
            }
            set
            {
                OnDesc_demandadoChanging(value);
                ReportPropertyChanging("Desc_demandado");
                _Desc_demandado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Desc_demandado");
                OnDesc_demandadoChanged();
            }
        }
        private global::System.String _Desc_demandado;
        partial void OnDesc_demandadoChanging(global::System.String value);
        partial void OnDesc_demandadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pequenoModel", Name="Expediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Expediente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Expediente object.
        /// </summary>
        /// <param name="id_expediente">Initial value of the id_expediente property.</param>
        public static Expediente CreateExpediente(global::System.Decimal id_expediente)
        {
            Expediente expediente = new Expediente();
            expediente.id_expediente = id_expediente;
            return expediente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_expediente
        {
            get
            {
                return _id_expediente;
            }
            set
            {
                if (_id_expediente != value)
                {
                    Onid_expedienteChanging(value);
                    ReportPropertyChanging("id_expediente");
                    _id_expediente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_expediente");
                    Onid_expedienteChanged();
                }
            }
        }
        private global::System.Decimal _id_expediente;
        partial void Onid_expedienteChanging(global::System.Decimal value);
        partial void Onid_expedienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Num_expediente
        {
            get
            {
                return _Num_expediente;
            }
            set
            {
                OnNum_expedienteChanging(value);
                ReportPropertyChanging("Num_expediente");
                _Num_expediente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Num_expediente");
                OnNum_expedienteChanged();
            }
        }
        private global::System.String _Num_expediente;
        partial void OnNum_expedienteChanging(global::System.String value);
        partial void OnNum_expedienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> año
        {
            get
            {
                return _año;
            }
            set
            {
                OnañoChanging(value);
                ReportPropertyChanging("año");
                _año = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("año");
                OnañoChanged();
            }
        }
        private Nullable<global::System.Decimal> _año;
        partial void OnañoChanging(Nullable<global::System.Decimal> value);
        partial void OnañoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> fcve_junta
        {
            get
            {
                return _fcve_junta;
            }
            set
            {
                Onfcve_juntaChanging(value);
                ReportPropertyChanging("fcve_junta");
                _fcve_junta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fcve_junta");
                Onfcve_juntaChanged();
            }
        }
        private Nullable<global::System.Decimal> _fcve_junta;
        partial void Onfcve_juntaChanging(Nullable<global::System.Decimal> value);
        partial void Onfcve_juntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom_actor
        {
            get
            {
                return _nom_actor;
            }
            set
            {
                Onnom_actorChanging(value);
                ReportPropertyChanging("nom_actor");
                _nom_actor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nom_actor");
                Onnom_actorChanged();
            }
        }
        private global::System.String _nom_actor;
        partial void Onnom_actorChanging(global::System.String value);
        partial void Onnom_actorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> fcve_demandado
        {
            get
            {
                return _fcve_demandado;
            }
            set
            {
                Onfcve_demandadoChanging(value);
                ReportPropertyChanging("fcve_demandado");
                _fcve_demandado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fcve_demandado");
                Onfcve_demandadoChanged();
            }
        }
        private Nullable<global::System.Decimal> _fcve_demandado;
        partial void Onfcve_demandadoChanging(Nullable<global::System.Decimal> value);
        partial void Onfcve_demandadoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pequenoModel", Name="Junta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Junta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Junta object.
        /// </summary>
        /// <param name="cve_junta">Initial value of the cve_junta property.</param>
        public static Junta CreateJunta(global::System.Decimal cve_junta)
        {
            Junta junta = new Junta();
            junta.cve_junta = cve_junta;
            return junta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cve_junta
        {
            get
            {
                return _cve_junta;
            }
            set
            {
                if (_cve_junta != value)
                {
                    Oncve_juntaChanging(value);
                    ReportPropertyChanging("cve_junta");
                    _cve_junta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cve_junta");
                    Oncve_juntaChanged();
                }
            }
        }
        private global::System.Decimal _cve_junta;
        partial void Oncve_juntaChanging(global::System.Decimal value);
        partial void Oncve_juntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Desc_junta
        {
            get
            {
                return _Desc_junta;
            }
            set
            {
                OnDesc_juntaChanging(value);
                ReportPropertyChanging("Desc_junta");
                _Desc_junta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Desc_junta");
                OnDesc_juntaChanged();
            }
        }
        private global::System.String _Desc_junta;
        partial void OnDesc_juntaChanging(global::System.String value);
        partial void OnDesc_juntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentarios
        {
            get
            {
                return _Comentarios;
            }
            set
            {
                OnComentariosChanging(value);
                ReportPropertyChanging("Comentarios");
                _Comentarios = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentarios");
                OnComentariosChanged();
            }
        }
        private global::System.String _Comentarios;
        partial void OnComentariosChanging(global::System.String value);
        partial void OnComentariosChanged();

        #endregion
    
    }

    #endregion
    
}
